name: Create Release

on:
  push:
    tags:
      - 'v*' # Dispara o workflow quando uma tag for criada (ex: v1.0.0)

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Release automática do módulo Terraform.
            Consulte o README.adoc para obter a documentação atualizada.
          draft: false
          prerelease: false 