name: Terraform CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  terraform:
    name: Terraform Test and Document

    runs-on: ubuntu-latest

    env:
      TERRAFORM_VERSION: "1.9.2"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.44.1
      
      - name: Run TFLint
        run: tflint --init && tflint --format=compact --recursive

      - name: Terraform Validate
        run: terraform init && terraform validate
        working-directory: ./example

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ github.token }}
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: ./tests/go.sum

      - name: Run Terratest
        run: cd tests && go test -timeout 15m -v ./...
        working-directory: ./tests
        env:
          TF_VAR_api_key: ${{ secrets.MAGALU_API_KEY }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-dir: .
          output-file: README.adoc
          template: <!-- BEGIN_TF_DOCS -->\n\n{{ .Content }}\n\n<!-- END_TF_DOCS -->
          output-format: asciidoc table
          output-method: inject
          git-push: "true"
